FROM golang:1.9.2
MAINTAINER Toshiaki Baba<toshiaki@netmark.jp>

RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u golang.org/x/tools/cmd/goimports
RUN go get -u github.com/golang/lint/golint
RUN go get -u github.com/mitchellh/gox
